name: Continuous Integration
on:
  push:
    branches:
    - main
jobs:
  buid-and-push-image:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Start Azure Cosmos DB Emulator
      run: |
        Write-Host "Launching Cosmos DB Emulator"
        Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
        Start-CosmosDbEmulator
    - run: npm install
    - run: node app.js 
    - name: Stop Azure Cosmos DB Emulator
      run: |
        Write-Host "Stopping Cosmos DB Emulator"
        Stop-Process -Name "CosmosDB.Emulator" -Force

        