name: Continuous Integration
on:
  push:
    branches:
    - main
jobs:
  buid-and-push-image:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Start Azure Cosmos DB Emulator
      run: |
        Write-Host "Launching Cosmos DB Emulator"
        Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
        Start-CosmosDbEmulator
        Start-Sleep -Seconds 10 # Wait for the emulator to start
   
        