name: Continuous Integration
on:
  push:
    branches:
    - main
jobs:
  unit_tests:
    name: Run Node.js unit tests
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Start Azure Cosmos DB Emulator
      run: |
        Write-Host "Launching Cosmos DB Emulator"
        Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
        Start-CosmosDbEmulator
    - name: Install test runner
      run: npm install -g mocha
    - name: Run Node.js tests
      run: mocha
